# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5a8cff3c869d1d75160cdac622a677078f7a2f025c21f9daa8bb69c6f94753ed0bfc5cf775a917e044bef217e8faee7d3cc7e0c02365670295c1711a79ec6568

test:
  secret_key_base: 6f925a77ac5fe5dd78d8eaf190379e71ac9db3ac2ec674e5b0a6901488568549826845738f22121e50e95464ad0e6c0d9fd730f50c4cf5c00282de454991eb37

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
